### ISSUE TITLE
1.10.1 is out...

### ISSUE THREAD

**Issue by rggjan** [conda-forge/flask-caching-feedstock#10]

**Comment by chfischer** [comment]
Flask-caching is currently breaking my env.. There is an issue with the latest werkzeug:
werkzeug.posixemulation module was remove in werkzeug 2.0.0, but the available conda-forge package's version still uses this.. This was fixed flask-caching 1.10.1....

**Comment by halldc** [comment]
See #15. Please reopen this issue if the latest conda package isn't working for you.
