### ISSUE TITLE
volunteering as maintainer

### ISSUE THREAD

**Issue by ap--** [conda-forge/flask-caching-feedstock#11]
Hi @halldc 

I'd be happy to help with maintaining this feedstock.
You would just have to open an issue in the feedstock repository with the following title
```
@conda-forge-admin, please add user @ap--
```
as described here: https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

Cheers,
Andreas 😃

**Comment by halldc** [comment]
Thanks Andreas! I've added you as a maintainer 👍
