### ISSUE TITLE
Issue with superset v3.0.1

### ISSUE THREAD

**Issue by xmnlab** [conda-forge/flask-caching-feedstock#23]
### Comment:

Hi everyone, 

We are trying to cut a release for superset v3.0.1 on conda-forge, but it has an issue with flask-caching:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=812320&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

superset depends on "flask>=2.2.5,<3.0.0" and "flask-caching>=1.11.1,<2.0"

The PR that added the version 1.11.1 is this one, and it add a pinning for flask: https://github.com/conda-forge/flask-caching-feedstock/pull/17/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR23

But flask-caching 1.11.1 doesn't have any pinning for flask: https://github.com/pallets-eco/flask-caching/blob/v1.11.1/setup.py#L6

in the flask-caching github repo, I can see that after that release they added the pinning to flask: https://github.com/pallets-eco/flask-caching/commit/b74ccaf40599802a5030e206df9d5001b65a57df#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R6

but few months later they removed that pinning: https://github.com/pallets-eco/flask-caching/commit/7a49ad2c0f4a82093e0e42a1014b8709cfcf4959

so my question is: is this pinning really necessary? because otherwise we cannot have the superset v3.0.1 on conda forge yet, but if that works with pypi (I am assuming that it is working), I would say that it would be ok to remove that constraint ... but I am an outsider here ... I don't have any experience with flask-caching 

any thoughts about that?

**Comment by ap--** [comment]
As of now, it seems already newer version of superset are available on conda-forge, which is why I will close this issue.
Please re-open if this is still blocking.
